### ISSUE TITLE
Wireframes and Layout and Style

### ISSUE THREAD

**Issue by chtakahashi** [mohicans-pop-2008/vinto#6]
- [x] Create Project Title
- [ ] Create basic visual imaginings of how the app will look -> Translate to figma wireframe
- [ ] Plan out how this will play out using CSS Grid and FlexBox
- [ ] Create basic UI element imaginings
- [ ] For Tomorrow (10/14) - Research FlexBox and CSS Grid

*Components*

- [x] Audio track component
- [x] UI Container
  - [x] Main content window
    - [ ] Video window gallery mode
    - [ ] Expect Video cells to automatically resize and position themselves.
    - [ ] Screen share window
  - [ ] Meeting controls bottom bar
    - [x] Screen share button
    - [x] Mute/Unmute button
    - [x] Video On/Off button
    - [x] Raise/lower hand button
  - [ ] Icons side bar
    - [x] Engagement score icon
    - [x] Hands raised icon

**Comment by khu-md** [comment]
Made some progress on this today using CSS Grid Layout and Flexbox. More to share tomorrow.

**Comment by khu-md** [comment]
Superseded by #49
